  // Color options with hex values
    export const enColors = [
        { value: "black", name: "Black", hex: "#000000" },
        { value: "white", name: "White", hex: "#FFFFFF" },
        { value: "red", name: "Red", hex: "#FF0000" },
        { value: "blue", name: "Blue", hex: "#0000FF" },
        { value: "green", name: "Green", hex: "#008000" },
        { value: "yellow", name: "Yellow", hex: "#FFFF00" },
        { value: "purple", name: "Purple", hex: "#800080" },
        { value: "pink", name: "Pink", hex: "#FFC0CB" },
        { value: "orange", name: "Orange", hex: "#FFA500" },
        { value: "brown", name: "Brown", hex: "#A52A2A" },
        { value: "gray", name: "Gray", hex: "#808080" },
        { value: "gold", name: "Gold", hex: "#FFD700" },
        { value: "silver", name: "Silver", hex: "#C0C0C0" },
        { value: "beige", name: "Beige", hex: "#F5F5DC" },
        { value: "ivory", name: "Ivory", hex: "#FFFFF0" },
        { value: "champagne", name: "Champagne", hex: "#F7E7CE" },
    ]

    export const arColors = [
        { value: "أسود",name: "أسود", hex: "#000000" },
        { value: "أبيض",name: "أبيض", hex: "#FFFFFF" },
        { value: "أحمر",name: "أحمر", hex: "#FF0000" },
        { value: "أزرق",name: "أزرق", hex: "#0000FF" },
        { value: "أخضر",name: "أخضر", hex: "#008000" },
        { value: "أصفر",name: "أصفر", hex: "#FFFF00" },
        { value: "أرجواني",name: "أرجواني", hex: "#800080" },
        { value: "وردي",name: "وردي", hex: "#FFC0CB" },
        { value: "برتقالي",name: "برتقالي", hex: "#FFA500" },
        { value: "البرتقالي",name: "البرتقالي", hex: "#FFA500" },
        { value: "بني",name: "بني", hex: "#A52A2A" },
        { value: "رمادي",name: "رمادي", hex: "#808080" },
        { value: "ذهبي",name: "ذهبي", hex: "#FFD700" },
        { value: "فضي",name: "فضي", hex: "#C0C0C0" },
        { value: "بيج",name: "بيج", hex: "#F5F5DC" },
        { value: "عاجي",name: "عاجي", hex: "#FFFFF0" },
        { value: "شامبين",name: "شامبين", hex: "#F7E7CE" },
    ];