export const featuredContent = {
  title: "Featured Dresses",
  description: "Discover our most popular dresses across all categories",
  viewAllButton: {
    text: "View All Dresses",
    href: "/products",
  },
  filterTags: ["All", "New", "Used", "Rental", "Wedding", "Evening", "Formal"],
  discount: {
    text: "40% OFF",
    animationConfig: {
      showDuration: 3000,  // Show for 3 seconds
      hideDuration: 500,   // Hide for 0.5 seconds
      transition: {
        spring: {
          stiffness: 300,
          damping: 15,
        },
        duration: 0.2,
      },
    },
  },
  badgeColors: {
    New: "bg-green-500",
    Used: "bg-amber-500",
    Rental: "bg-purple-500",
  },
  products: [
    {
      id: 1,
      name: "Elegant Evening Gown",
      vendor: "Elegance",
      price: "299",
      originalPrice: "399",
      image: "https://images.unsplash.com/photo-1605763240000-7e93b172d754?q=80&w=1000&auto=format&fit=crop",
      type: "New",
      rating: 4.8,
      reviewCount: 24,
      totalSales: 128,
    },
    {
      id: 2,
      name: "Vintage Wedding Dress",
      vendor: "Bella Boutique",
      price: "199",
      image: "https://images.unsplash.com/photo-1596436889106-be35e843f974?q=80&w=1000&auto=format&fit=crop",
      type: "Used",
      rating: 4.5,
      reviewCount: 18,
      totalSales: 76,
    },
    {
      id: 3,
      name: "Designer Cocktail Dress",
      vendor: "Glamour",
      price: "89",
      image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop",
      type: "Rental",
      rating: 4.2,
      reviewCount: 32,
      totalSales: 215,
    },
    {
      id: 4,
      name: "Formal Ball Gown",
      vendor: "Dress Haven",
      price: "349",
      originalPrice: "499",
      image: "https://images.unsplash.com/photo-1550639525-c97d455acf70?q=80&w=1000&auto=format&fit=crop",
      type: "New",
      rating: 4.9,
      reviewCount: 42,
      totalSales: 94,
    },
    {
      id: 5,
      name: "Summer Wedding Guest Dress",
      vendor: "Chic Collection",
      price: "129",
      image: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=1000&auto=format&fit=crop",
      type: "Used",
      rating: 4.3,
      reviewCount: 15,
      totalSales: 63,
    },
    {
      id: 6,
      name: "Red Carpet Gown",
      vendor: "Runway Ready",
      price: "120",
      image: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1000&auto=format&fit=crop",
      type: "Rental",
      rating: 4.7,
      reviewCount: 28,
      totalSales: 182,
    },
    {
      id: 7,
      name: "Bohemian Maxi Dress",
      vendor: "Style Studio",
      price: "159",
      image: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?q=80&w=1000&auto=format&fit=crop",
      type: "New",
      rating: 4.6,
      reviewCount: 37,
      totalSales: 156,
    },
    {
      id: 8,
      name: "Prom Night Special",
      vendor: "Dress Dreams",
      price: "179",
      originalPrice: "249",
      image: "https://images.unsplash.com/photo-1562137369-1a1a0bc66744?q=80&w=1000&auto=format&fit=crop",
      type: "Used",
      rating: 4.4,
      reviewCount: 22,
      totalSales: 89,
    },
  ],
  defaultProductConfig: {
    selectedSize: "m",
    selectedColor: "black",
  },
  sliderConfig: {
    scrollMultiplier: 1.5,
    cursorGrab: "grab",
    cursorGrabbing: "grabbing",
  },
}